export function renderIntegral(root,analysis){
 root.replaceChildren();if(!analysis)return;const a=analysis.integral,el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 root.append(el('h3','Resumen para cliente'),el('p',a.conclusion));const badge=el('p',a.balance);badge.className='integral-balance';root.append(badge);
 const grid=el('div');grid.className='use-grid';for(const cat of [...a.ordered,...a.categories.filter(c=>!a.ordered.includes(c))]){const card=el('details');card.className='use-card';const summary=el('summary');summary.append(el('strong',cat.name),el('span',cat.score===null?'Sin referencia':`${cat.score.toFixed(1)} / 10 · ${cat.level}`));const meter=el('progress');meter.max=10;meter.value=cat.score||0;meter.setAttribute('aria-label',cat.name);summary.append(meter);card.append(summary,el('p',cat.description));for(const t of cat.details){const line=el('div');line.className='use-task';line.append(el('strong',t.name),el('span',t.score===null?'Sin referencia':`${t.score.toFixed(1)} / 10 · ${t.level}`),el('p',t.note));if(t.missing?.length)line.append(el('p','Falta: '+t.missing.join(', ')));if(t.requirements)line.append(el('small',`Objetivo de memoria: ${t.requirements.ramTarget} GB RAM${t.requirements.vramTarget?' · '+t.requirements.vramTarget+' GB VRAM':''}. No es un requisito oficial ni una garantía de compatibilidad.`));card.append(line);}grid.append(card);}root.append(grid);
 for(const [title,list]of [['Ideal para',a.ideal],['Fortalezas',a.strengths],['A tener en cuenta',a.limitations]]){root.append(el('h4',title));const ul=el('ul');for(const item of list)ul.append(el('li',item));if(!list.length)ul.append(el('li',title==='A tener en cuenta'?'No detectamos límites adicionales con los datos informados.':'Sin referencias suficientes para destacar usos.'));root.append(ul);}
 root.append(el('h4','Upgrades según tu uso'));if(!a.upgrades.length)root.append(el('p','No requiere upgrades prioritarios para los usos recomendados.'));for(const u of a.upgrades)root.append(el('p',`${u.current} → ${u.recommended}. ${u.benefit} ${u.scope} Confirmá compatibilidad antes de comprar.`));
 const technical=el('details');technical.append(el('summary','Análisis técnico y metodología'));const f=a.facts;technical.append(el('p',`CPU: ${f.cores||'no informados'} núcleos · Hilos: ${f.threads||'no informados por el catálogo'} · Arquitectura: ${f.architecture||'sin dato'}. RAM: ${f.ramType||'tipo no informado'} · ${f.ramFrequency?f.ramFrequency+' MT/s':'frecuencia no informada'}. VRAM: ${f.vram?f.vram+' GB':'compartida o no informada'}.`),el('p',`Confianza del análisis: ${a.confidence==='low'?'baja':'media'}. Las puntuaciones son índices de adecuación estimados, redondeados a 0,5; no son benchmarks ni porcentajes de rendimiento. Las medias raster solo calibran una aproximación gráfica: no equivalen a benchmarks de aplicaciones.`));
 for(const t of a.tasks){const d=el('details');d.append(el('summary',t.name));const w=t.requirements.weights;d.append(el('p',`Pesos: ${Object.entries(w).map(([key,value])=>`${key}: ${Math.round(value*100)}%`).join(' · ')}. Objetivos normalizados CPU: ${t.requirements.cpuTarget} · GPU: ${t.requirements.gpuTarget} · RAM: ${t.requirements.ramTarget} GB · VRAM: ${t.requirements.vramTarget||'no aplica'} GB. ${t.requirements.parallel?'Incluye una aproximación por núcleos; no asume que todos son equivalentes.':'Prioriza respuesta de CPU.'}`));technical.append(d);}const link=el('a','Ver fuentes, escala, supuestos y límites');link.href='ANALYSIS.md';link.target='_blank';link.rel='noopener';technical.append(link);root.append(technical,el('p','Valoraciones orientativas para las cargas descritas. Comprobá requisitos de software, drivers y compatibilidad; no se prometen tiempos de render, modelos de IA ni certificaciones profesionales.'));
}

