import {cpus,gpus,detect,estimate,rating,makeBudget} from './engine.mjs';
const $=id=>document.getElementById(id);let mode='gaming',current=null,analysis=null,card=null,budgets=[];
for(const [id,list] of [['cpu',cpus],['gpu',gpus]])for(const [name]of list){const o=document.createElement('option');o.value=o.textContent=name;$(id).append(o);}
const spec=()=>Object.fromEntries(['cpu','gpu','ram','storage','capacity'].map(k=>[k,$(k).value]));
function fill(s){for(const k of ['cpu','gpu','ram','storage','capacity'])$(k).value=s[k]??'';}
function clear(){current=null;analysis=null;card=null;$('export').disabled=$('save').disabled=true;$('ready').textContent='POR ANALIZAR';$('results').replaceChildren();$('warnings').replaceChildren();$('card-preview').replaceChildren();const e=document.createElement('div');e.className='empty';e.textContent='Revisá los componentes y volvé a analizar para actualizar los resultados.';$('results').append(e);}
function render(){
 $('gaming').classList.toggle('selected',mode==='gaming');$('productivity').classList.toggle('selected',mode==='productivity');$('gaming').setAttribute('aria-pressed',mode==='gaming');$('productivity').setAttribute('aria-pressed',mode==='productivity');$('resolution').hidden=mode!=='gaming';$('result-title').textContent=mode==='gaming'?'Rendimiento en juegos':'Rendimiento para trabajar';$('result-subtitle').textContent=mode==='gaming'?'Calidad media · Sin ray tracing ni reescalado':'Capacidad relativa · Proyectos y tareas moderadas';
 if(!current)return;analysis=estimate(current,$('resolution').value);$('results').replaceChildren();
 for(const [i,item]of analysis[mode].entries()){const el=document.createElement('article');el.className='game';const mark=document.createElement('div');mark.className='icon';mark.textContent=mode==='gaming'?`JUEGO / 0${i+1}`:`APLICACIÓN / 0${i+1}`;const title=document.createElement('h3');title.textContent=item.name;const val=document.createElement('strong');val.textContent=mode==='gaming'?`${item.min}–${item.max} `:`${item.score} `;const unit=document.createElement('small');unit.textContent=mode==='gaming'?'FPS':'/ 100';val.append(unit);const note=document.createElement('p');note.textContent=mode==='gaming'?'Rango orientativo':rating(item.score);el.append(mark,title,val);if(mode==='productivity'){const bar=document.createElement('div');bar.className='bar';const b=document.createElement('i');b.style.width=item.score+'%';bar.append(b);el.append(bar);}el.append(note);$('results').append(el);}
 $('warnings').replaceChildren();for(const w of analysis.warnings){const p=document.createElement('p');p.textContent=w;$('warnings').append(p);}$('ready').textContent='ESTIMACIÓN LISTA';$('export').disabled=$('save').disabled=false;drawCard();
}
$('gaming').onclick=()=>{mode='gaming';render();};$('productivity').onclick=()=>{mode='productivity';render();};$('resolution').onchange=render;
$('form').addEventListener('input',()=>{if(current)clear();});$('form').onsubmit=e=>{e.preventDefault();const s=spec();if(!estimate(s)){$('status').textContent='Completá CPU, GPU, RAM, tipo y capacidad de almacenamiento.';return;}current=s;render();};
$('demo').onclick=()=>{fill({cpu:'Ryzen 5 5600',gpu:'RTX 3060',ram:16,storage:'NVMe',capacity:1000});current=spec();$('status').textContent='Ejemplo cargado: Ryzen 5 5600 + RTX 3060. Podés editarlo.';render();};
let uploadVersion=0;
async function readPDF(file){const version=++uploadVersion;clear();fill({});if(!file)return;if(file.size>15*1024*1024){$('status').textContent='El archivo supera los 15 MB.';return;}if(!/\.pdf$/i.test(file.name)){$('status').textContent='Elegí un archivo PDF.';return;}$('status').textContent='Leyendo el presupuesto…';$('pdf').disabled=true;let task;
 try{const pdfjs=await import('./vendor/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.mjs',import.meta.url).href;task=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),standardFontDataUrl:new URL('./vendor/standard_fonts/',import.meta.url).href,isEvalSupported:false});const pdf=await task.promise;if(pdf.numPages>50)throw new Error('pages');let text='';for(let page=1;page<=pdf.numPages;page++){const content=await(await pdf.getPage(page)).getTextContent();text+=content.items.map(i=>i.str+(i.hasEOL?'\n':' ')).join('')+'\n';}if(version!==uploadVersion)return;if(!text.trim()){$('status').textContent='El PDF parece escaneado. Este MVP no incluye OCR: cargá los componentes manualmente.';return;}const data=detect(text);fill(data);const missing=['cpu','gpu','ram','storage','capacity'].filter(k=>!data[k]);$('status').textContent=`${file.name}: ${missing.length?'faltan datos o hay modelos fuera del catálogo. Completalos manualmente.':'componentes detectados.'} Revisá todos los campos antes de analizar.`;
 }catch(err){if(version===uploadVersion)$('status').textContent=err.message==='pages'?'El PDF supera el límite de 50 páginas.':err.name==='PasswordException'?'El PDF está protegido con contraseña. Subí una copia sin protección o ingresá los datos.':'No pudimos leer este PDF. Probá otro archivo o ingresá los componentes.';}finally{await task?.destroy();if(version===uploadVersion)$('pdf').disabled=false;}}
$('pdf').onchange=e=>readPDF(e.target.files[0]);for(const event of ['dragover','dragenter'])$('drop').addEventListener(event,e=>{e.preventDefault();$('drop').classList.add('drag');});$('drop').addEventListener('dragleave',()=>$('drop').classList.remove('drag'));$('drop').addEventListener('drop',e=>{e.preventDefault();$('drop').classList.remove('drag');readPDF(e.dataTransfer.files[0]);});
function drawCard(){card=document.createElement('canvas');card.width=1080;card.height=1920;card.setAttribute('aria-label','Vista previa de la placa compartible');const c=card.getContext('2d');c.fillStyle='#f7fafc';c.fillRect(0,0,1080,1920);c.fillStyle='#b2e8fc';c.fillRect(0,0,1080,18);const text=(s,x,y,size=32,color='#17212b')=>{c.fillStyle=color;c.font=`${size}px Arial`;c.fillText(s,x,y);};text('PC PERFORMANCE',80,125,30);text('ANALYZER',80,166,30);text('TU PC. SU POTENCIAL.',80,280,58);text(mode==='gaming'?`GAMING · ${$('resolution').value}`:'PRODUCTIVIDAD',80,355,28,'#3988a7');c.fillStyle='#17212b';c.fillRect(80,415,920,290);text(current.cpu,120,478,34,'#fff');text(current.gpu,120,538,34,'#b2e8fc');text(`${current.ram} GB RAM`,120,604,28,'#fff');text(`${current.storage} · ${current.capacity} GB`,120,660,28,'#fff');let y=790;for(const item of analysis[mode]){text(item.name,80,y,34);text(mode==='gaming'?`${item.min}–${item.max} FPS`:`${item.score}/100 · ${rating(item.score)}`,80,y+57,42);c.fillStyle='#dcebf1';c.fillRect(80,y+88,920,2);y+=mode==='gaming'?190:140;}text('ESTIMACIONES ORIENTATIVAS',80,1720,25,'#527180');text('Modelo heurístico · No son benchmarks medidos.',80,1770,25,'#527180');text(mode==='gaming'?'Calidad media · Sin RT ni reescalado.':'Puntajes relativos para tareas moderadas.',80,1815,25,'#527180');text('El rendimiento real puede variar.',80,1860,25,'#527180');$('card-preview').replaceChildren(card);}
$('export').onclick=()=>card?.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download='pc-performance-1080x1920.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');
$('save').onclick=()=>{if(!current)return;if(budgets.length===3){$('saved').textContent='Límite de tres presupuestos en esta pestaña.';return;}budgets.push(makeBudget(current,`Presupuesto ${budgets.length+1}`));$('saved').textContent=`${budgets.length}/3 guardados en esta pestaña.`;};
