import {cpus,gpus,estimate,makeBudget,RESOLUTIONS} from './engine.mjs';import {parseBudget} from './parser.mjs';import {extractDocument} from './document.mjs';import {loadIcons,iconURL} from './games.mjs';import {createReport,formatFPS,gpuLabel,ramLabel} from './report.mjs';
const $=id=>document.getElementById(id);let mode='gaming',current=null,analysis=null,card=null,budgets=[],extracted={},controller=null;let version=0;const iconsPromise=loadIcons();
const fields=['cpu','gpu','gpuVram','ram','ramType','ramFrequency','ramModules','storage','capacity','motherboard','psu','cooling','case'];
for(const [id,list]of [['cpu-options',cpus],['gpu-options',gpus]])for(const [name]of list){const o=document.createElement('option');o.value=name;$(id).append(o);}
const spec=()=>({...extracted,...Object.fromEntries(fields.map(k=>[k,$(k).value]))});
function fill(s){extracted=s;for(const k of fields)$(k).value=s[k]??'';}
function node(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function clear(){version++;current=null;analysis=null;card=null;$('export').removeAttribute('href');$('export').setAttribute('aria-disabled','true');$('share').disabled=$('save').disabled=true;$('ready').textContent='POR ANALIZAR';$('results').replaceChildren(node('div','Confirmá los componentes para calcular el rendimiento.','empty'));$('warnings').replaceChildren();$('resolution-summary').replaceChildren();$('conclusion').textContent='';$('card-preview').replaceChildren();}
function showDetection(s){$('detection').hidden=false;$('detected-summary').textContent=[s.cpu,s.gpu?gpuLabel(s):'',s.ram?ramLabel(s):'',s.capacity?`${s.capacity>=1000?s.capacity/1000+' TB':s.capacity+' GB'} ${s.storage}`:''].filter(Boolean).join(' · ');$('evidence').replaceChildren();for(const k of fields){if(!s.evidence?.[k])continue;const line=node('p',`${({cpu:'CPU',gpu:'GPU',ram:'RAM',storage:'Disco',motherboard:'Motherboard',psu:'Fuente',cooling:'Refrigeración',case:'Gabinete'})[k]||k}: ${s.evidence[k]}`);$('evidence').append(line);}for(const issue of s.issues||[])$('evidence').append(node('p',issue,'parse-issue'));}
async function render(){const token=++version;
 $('gaming').classList.toggle('selected',mode==='gaming');$('productivity').classList.toggle('selected',mode==='productivity');$('gaming').setAttribute('aria-pressed',mode==='gaming');$('productivity').setAttribute('aria-pressed',mode==='productivity');$('resolution').hidden=$('preset').hidden=mode!=='gaming';$('result-title').textContent=mode==='gaming'?'Compará el rendimiento por resolución':'Capacidad para trabajar';$('result-subtitle').textContent=mode==='gaming'?'Rangos estimados de FPS · Resolución nativa · Sin RT ni reescalado':'Niveles orientativos para proyectos moderados';
 if(!current)return;analysis=estimate(current,$('resolution').value,$('preset').value);$('results').replaceChildren();$('results').className=mode==='gaming'?'results table-results':'results';
 if(mode==='gaming'){
  const table=node('table');const head=node('thead');const row=node('tr');for(const label of ['Juego','1080p','1440p / 2K','2160p / 4K'])row.append(node('th',label));head.append(row);table.append(head);const body=node('tbody');for(const game of analysis.gaming){const tr=node('tr');const name=node('td');const label=node('div',undefined,'game-label');const image=node('img');image.src=iconURL(game);image.alt='';image.width=image.height=32;label.append(image,node('strong',game.name));name.append(label);tr.append(name);for(const res of RESOLUTIONS){const td=node('td',formatFPS(game.values[res]));td.classList.toggle('focus-resolution',res===$('resolution').value);tr.append(td);}body.append(tr);}table.append(body);$('results').append(table,node('p','GTA VI: sin FPS de PC fiables. Los iconos son recursos vectoriales propios.','table-note'));
 }else for(const item of analysis.productivity){const article=node('article',undefined,'game');article.append(node('h3',item.name),node('strong',item.level,'work-level'),node('p',item.note));$('results').append(article);}
 $('resolution-summary').replaceChildren();if(mode==='gaming')for(const summary of analysis.summary){const item=node('div',undefined,'resolution-card');item.classList.toggle('recommended',summary.resolution===analysis.recommended);item.append(node('span',summary.resolution==='1440p'?'1440p / 2K':summary.resolution),node('strong',summary.level));$('resolution-summary').append(item);}
 $('conclusion').textContent=mode==='gaming'?analysis.conclusion:'Los niveles describen tareas moderadas. Para proyectos profesionales complejos, revisá RAM, VRAM, codecs, efectos y proxies.';
 $('warnings').replaceChildren();for(const w of [...(extracted.issues||[]),...analysis.warnings])$('warnings').append(node('p',w));$('ready').textContent='ESTIMACIÓN LISTA';$('save').disabled=false;$('export').disabled=$('share').disabled=true;
 const icons=await iconsPromise;if(token!==version)return;card=createReport(current,analysis,mode,icons);$('card-preview').replaceChildren(card);$('export').href=card.toDataURL('image/png');$('export').download=`pc-performance-${mode}-1080x1920.png`;$('export').setAttribute('aria-disabled','false');$('export').disabled=false;$('share').disabled=false;
}
$('gaming').onclick=()=>{mode='gaming';render();};$('productivity').onclick=()=>{mode='productivity';render();};$('resolution').onchange=render;$('preset').onchange=render;
$('form').addEventListener('input',()=>{if(current)clear();});$('form').onsubmit=e=>{e.preventDefault();const s=spec();if(!estimate(s)){$('status').textContent='Solo necesitamos el procesador, la gráfica y la cantidad de RAM. Los otros campos son opcionales.';return;}current=s;render();};
$('demo').onclick=()=>{controller?.abort();fill(parseBudget('Procesador: AMD Ryzen 7 9700X\nVGA MSI GEFORCE RTX5070TI 16G GAMING\nMemoria: Kingston Fury 32 GB DDR5 6000 MHz (2x16GB)\nSSD: Kingston NVMe 1TB\nMotherboard: MSI B650 Gaming\nFuente: 750W 80 Plus Gold\nCooler: Thermalright Peerless Assassin\nGabinete: Corsair 4000D'));current=spec();showDetection(extracted);$('status').textContent='Ejemplo cargado. Podés corregir cualquier componente.';render();};
async function readPDF(file){if(!file)return;controller?.abort();controller=new AbortController();const active=controller;clear();$('detection').hidden=true;fill({});if(file.size>15*1024*1024){$('status').textContent='El PDF supera los 15 MB.';return;}if(!/\.pdf$/i.test(file.name)){$('status').textContent='Elegí un archivo PDF.';return;}$('pdf').disabled=true;$('cancel-read').hidden=false;$('status').textContent='Leyendo el documento…';
 try{const document=await extractDocument(file,message=>{if(active===controller)$('status').textContent=message;},active.signal);if(active!==controller||active.signal.aborted)return;const data=parseBudget(document.text);data.documentMeta={name:file.name,ocrPages:document.ocrPages,ocrConfidence:document.ocrConfidence};if(document.partial)data.issues.push('OCR limitado a 8 páginas escaneadas. El resto conserva el texto extraíble; el documento puede estar incompleto.');if(document.ocrPages)data.issues.push(`Se usó OCR en ${document.ocrPages} página(s). Revisá especialmente las cifras y los sufijos de los modelos.`);fill(data);showDetection(data);const missing=['cpu','gpu','ram'].filter(k=>!data[k]);$('status').textContent=missing.length?`Detectamos la información disponible. Solo falta ${missing.map(k=>({cpu:'CPU',gpu:'GPU',ram:'cantidad de RAM'})[k]).join(', ')} para estimar.`:`Detectamos esta PC en ${file.name}. Confirmá los componentes para analizar.`;
 }catch(error){console.error("PDF extraction:",error.name,error.message);if(active===controller)$('status').textContent=error.name==='AbortError'||active.signal.aborted?'Lectura cancelada.':error.message==='pages'?'El PDF supera el límite de 50 páginas.':error.name==='PasswordException'?'PDF protegido: subí una copia sin contraseña.':'No pudimos interpretar el documento. Podés pegar su texto o cargar solo los tres datos principales.';}finally{if(active===controller){$('pdf').disabled=false;$('pdf').value='';$('cancel-read').hidden=true;}}}
$('pdf').onchange=e=>readPDF(e.target.files[0]);$('cancel-read').onclick=()=>controller?.abort();for(const ev of ['dragenter','dragover'])$('drop').addEventListener(ev,e=>{e.preventDefault();$('drop').classList.add('drag');});$('drop').addEventListener('dragleave',()=>$('drop').classList.remove('drag'));$('drop').addEventListener('drop',e=>{e.preventDefault();$('drop').classList.remove('drag');readPDF(e.dataTransfer.files[0]);});
$('parse-text').onclick=()=>{clear();const data=parseBudget($('budget-text').value);fill(data);showDetection(data);$('status').textContent='Texto interpretado. Revisá y confirmá los componentes.';};
function download(blob){const url=URL.createObjectURL(blob);const a=node('a');a.href=url;a.download=`pc-performance-${mode}-1080x1920.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
$('export').onclick=()=>{if(!card)return false;};
$('share').onclick=()=>{if(!card)return;card.toBlob(async blob=>{if(!blob)return;const file=new File([blob],`pc-performance-${mode}.png`,{type:'image/png'});try{if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'PC Performance Analyzer'});else{download(blob);$('status').textContent='Placa descargada. Adjuntala desde WhatsApp o tu aplicación de mensajería.';}}catch(error){if(error.name!=='AbortError'){$('status').textContent='No se pudo compartir. Descargá la placa para enviarla.';}}},'image/png');};
$('save').onclick=()=>{if(!current)return;if(budgets.length>=3){$('saved').textContent='Ya guardaste tres presupuestos en esta pestaña.';return;}budgets.push(makeBudget(current,`Presupuesto ${budgets.length+1}`));$('saved').textContent=`${budgets.length}/3 guardados en esta pestaña.`;};

