import {mkdir,copyFile,cp,readdir} from 'node:fs/promises';
import {createRequire} from 'node:module';import {dirname} from 'node:path';
const require=createRequire(import.meta.url);
await mkdir('dist/vendor',{recursive:true});
for(const f of ['index.html','style.css','app.mjs','engine.mjs','hardware.mjs','parser.mjs','document.mjs','games.mjs','report.mjs','favicon.svg']) await copyFile(f,`dist/${f}`);
for(const f of ['pdf.mjs','pdf.worker.mjs']) await copyFile(`node_modules/pdfjs-dist/build/${f}`,`dist/vendor/${f}`);
await cp('node_modules/pdfjs-dist/standard_fonts','dist/vendor/standard_fonts',{recursive:true});
await cp('node_modules/pdfjs-dist/wasm','dist/vendor/pdf-wasm',{recursive:true});
await mkdir('dist/vendor/ocr/lang',{recursive:true});await mkdir('dist/vendor/ocr/core',{recursive:true});
for(const f of ['tesseract.esm.min.js','worker.min.js','worker.min.js.LICENSE.txt','tesseract.min.js.LICENSE.txt']) await copyFile(`node_modules/tesseract.js/dist/${f}`,`dist/vendor/ocr/${f}`);
const core=dirname(require.resolve('tesseract.js-core',{paths:[dirname(require.resolve('tesseract.js'))]}));
for(const f of await readdir(core))if(/\.wasm(?:\.js)?$/.test(f))await copyFile(`${core}/${f}`,`dist/vendor/ocr/core/${f}`);
for(const lang of ['eng','spa'])await copyFile(`node_modules/@tesseract.js-data/${lang}/4.0.0_best_int/${lang}.traineddata.gz`,`dist/vendor/ocr/lang/${lang}.traineddata.gz`);
console.log('Static production build ready');
