// Downloads data only; no code from the source repository is executed.
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const revision='c52a04ca9465c83997ed335f7767b09a2005dd26';
const source='https://github.com/docyx/pc-part-dataset';
const local=process.argv.includes('--local');
const categories=['cpu','video-card','motherboard','memory'];
await mkdir('catalog-source',{recursive:true});
const digest={};const raw={};
for(const category of categories){
 const path=`catalog-source/${category}.json`;
 if(!local){const response=await fetch(`https://raw.githubusercontent.com/docyx/pc-part-dataset/${revision}/data/json/${category}.json`);if(!response.ok)throw Error(`Download ${category}: ${response.status}`);await writeFile(path,await response.text());}
 const bytes=await readFile(path);digest[category]=createHash('sha256').update(bytes).digest('hex');raw[category]=JSON.parse(bytes);
 if(!Array.isArray(raw[category])||raw[category].some(p=>typeof p.name!=='string'||p.name.length>250))throw Error(`Invalid catalog ${category}`);
}
const cpu=raw.cpu.map(p=>[p.name,p.core_count,p.core_clock,p.boost_clock,p.microarchitecture,p.tdp,p.graphics]);
const gpu=raw['video-card'].map(p=>[p.name,p.chipset,p.memory]);
const motherboard=raw.motherboard.map(p=>[p.name,p.socket,p.form_factor,p.max_memory,p.memory_slots]);
const memory=raw.memory.map(p=>[p.name,p.speed,p.modules,p.cas_latency]);
const counts=Object.fromEntries(categories.map(c=>[c,raw[c].length]));
const metadata={source,revision,downloadedAt:new Date().toISOString(),sourceUpdatedAt:'2025-07-23',license:'MIT',counts,sha256:digest};
await writeFile('catalog-data.mjs',`// Generated by catalog-import.mjs. See CATALOG-LICENSE.txt and CATALOG.md.\nexport const metadata=${JSON.stringify(metadata)};\nexport const cpuRows=${JSON.stringify(cpu)};\nexport const gpuRows=${JSON.stringify(gpu)};\nexport const motherboardRows=${JSON.stringify(motherboard)};\nexport const memoryRows=${JSON.stringify(memory)};\n`);
if(!local){const response=await fetch(`https://raw.githubusercontent.com/docyx/pc-part-dataset/${revision}/LICENSE`);if(!response.ok)throw Error('Catalog license download failed');await writeFile('CATALOG-LICENSE.txt',await response.text());}
console.log(JSON.stringify({counts,revision}));
