import {createComparisonReport} from './comparison-report.mjs';
import {compareBudgets} from './comparison.mjs';
import {formatFPS,ramLabel,gpuLabel} from './report.mjs';
const el=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;};
export function mountComparison({getBudgets,onLoad,onRemove,onRename}){
 const controls=document.getElementById('compare-controls'),cards=document.getElementById('compare-cards'),results=document.getElementById('compare-results'),status=document.getElementById('compare-status');
 const selectors=['compare-mode','compare-resolution','compare-preset'].map(id=>document.getElementById(id));for(const select of selectors)select.onchange=render;
 const download=document.getElementById('compare-export');download.onclick=()=>{const b=getBudgets();if(b.length<2)return false;const canvas=createComparisonReport(b,selectors[1].value,selectors[2].value,selectors[0].value);download.href=canvas.toDataURL('image/png');download.download='pc-comparacion-'+selectors[0].value+'.png';};
 function render(){const budgets=getBudgets();const mode=selectors[0].value;selectors[1].hidden=selectors[2].hidden=mode!=='gaming';controls.hidden=budgets.length<2;cards.replaceChildren();results.replaceChildren();status.textContent=budgets.length<2?'Agregá al menos dos PCs para ver la comparación.':`${budgets.length} PCs comparadas con los mismos criterios. ${mode==='gaming'?'Rangos estimados de FPS; sin RT ni reescalado.':'Niveles orientativos para tareas moderadas.'}`;
  for(const budget of budgets){const card=el('article',undefined,'compare-pc');const name=el('input');name.value=budget.name;name.maxLength=40;name.setAttribute('aria-label','Nombre de '+budget.name);name.oninput=()=>{onRename(budget.id,name.value.trim()||budget.name);const heading=results.querySelectorAll('thead th')[budgets.indexOf(budget)+1];if(heading)heading.textContent=budget.name;if(budgets.length>=2)document.getElementById("compare-preview").replaceChildren(createComparisonReport(budgets,selectors[1].value,selectors[2].value,mode));};name.onchange=render;card.append(name,el('p',budget.spec.cpu),el('p',gpuLabel(budget.spec)),el('p',ramLabel(budget.spec)));const actions=el('div',undefined,'compare-actions');const load=el('button','Revisar componentes','secondary');load.onclick=()=>onLoad(budget.id);const remove=el('button','Quitar','text-button');remove.onclick=()=>{onRemove(budget.id);render();};actions.append(load,remove);card.append(actions);cards.append(card);}
  document.getElementById('compare-export-area').hidden=budgets.length<2;if(budgets.length<2){document.getElementById('compare-preview').replaceChildren();return;}document.getElementById('compare-preview').replaceChildren(createComparisonReport(budgets,selectors[1].value,selectors[2].value,mode));const comparison=compareBudgets(budgets,selectors[1].value,selectors[2].value,mode);const table=el('table');const head=el('tr');head.append(el('th',mode==='gaming'?'Juego':'Tarea'));for(const budget of budgets)head.append(el('th',budget.name));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');
  const specs=[['Procesador',b=>b.spec.cpu],['GPU',b=>gpuLabel(b.spec)],['RAM',b=>ramLabel(b.spec)],['Disco',b=>b.spec.capacity?`${b.spec.capacity} GB ${b.spec.storage||''}`:b.spec.storage||'No informado']];for(const [label,read]of specs){const row=el('tr',undefined,'compare-hardware');row.append(el('th',label));for(const b of budgets)row.append(el('td',read(b)));body.append(row);}
  for(const item of comparison.rows){const row=el('tr');row.append(el('th',item.name));for(const value of item.values)row.append(el('td',mode==='gaming'?value?formatFPS(value):'Sin referencia':value));body.append(row);}table.append(body);results.append(table);
  for(const column of comparison.columns){for(const warning of column.analysis?.warnings||[])results.append(el('p',`${column.name}: ${warning}`,'compare-warning'));}
 }
 render();return render;
}



