import test from 'node:test';import assert from 'node:assert/strict';import {detect,parseBudget,estimate,makeBudget} from './engine.mjs';import {identifyCPU,identifyGPU,resolveCPU,resolveGPU} from './hardware.mjs';import {reconstructRows} from './document.mjs';
const s={cpu:'Ryzen 5 5600',gpu:'RTX 3060',ram:16,storage:'NVMe',capacity:1000};
test('Core Ultra 265KF quotation produces FPS in every game and resolution',()=>{
 const spec=parseBudget('CPU Intel Core Ultra 7 265KF\nGPU RTX 5070 Ti 16GB\nRAM DDR5 32GB 5600MHz\nSSD NVMe 1TB');
 const result=estimate(spec);assert.equal(spec.cpu,'Core Ultra 7 265KF');
 assert.equal(result.cpu.name,spec.cpu);assert.equal(result.cpu.equivalent,'Core Ultra 7 265K');
 for(const game of result.gaming)for(const res of ['1080p','1440p','4K']){assert.ok(game.values[res].min>0);assert.ok(game.values[res].max>game.values[res].min);}
 assert.ok(result.productivity.every(job=>job.score>0));assert.ok(result.warnings.some(w=>w.includes('265K')));
 assert.equal(resolveCPU('Core Ultra 7 999KF'),null);
});
test('detects a multiline quotation and RAM kit without using GPU VRAM',()=>{assert.deepEqual(detect('CPU AMD Ryzen 5 5600\nGPU NVIDIA RTX 3060 12GB\nMemoria DDR4 2 x 8 GB\nSSD M.2 NVMe 1 TB'),s);});
test('longer model wins and unknown hardware stays empty',()=>{assert.equal(detect('Ryzen 5 5600G\nRTX 3060 Ti').cpu,'Ryzen 5 5600G');assert.equal(detect('RTX 3060 Ti').gpu,'RTX 3060 Ti');assert.equal(detect('CPU desconocida GPU desconocida').cpu,'');});
test('resolution reduces FPS and productivity keeps old tasks and adds professional workloads',()=>{assert.ok(estimate(s,'4K').gaming[0].max<estimate(s).gaming[0].max);assert.equal(estimate(s).productivity.length,10);});
test('only critical missing components block analysis; unknown families do not get invented FPS',()=>{assert.equal(estimate({...s,gpu:''}).gaming[0].values['1080p'],null);assert.equal(estimate({...s,ram:0}),null);assert.ok(estimate({...s,capacity:'',storage:''}));assert.equal(estimate({...s,gpu:'RTX 6090'}).gaming[0].values['1080p'],null);});
test('budget records keep independent nested snapshots for future comparison',()=>{const original={...s,drives:[{capacity:1000}]};const b=makeBudget(original);original.ram=32;original.drives[0].capacity=2000;assert.equal(b.spec.ram,16);assert.equal(b.spec.drives[0].capacity,1000);assert.equal(b.schemaVersion,2);});
test('all commercial RTX 5070 Ti aliases normalize without a catalogue exact match',()=>{for(const alias of ['RTX5070TI','RTX 5070 TI','GEFORCE RTX 5070 Ti 16GB','VGA MSI RTX5070TI 16G GAMING'])assert.equal(identifyGPU(alias),'RTX 5070 Ti');});
test('modern CPU, VRAM, RAM kit, speed and all secondary parts survive extraction',()=>{const a=parseBudget('Procesador AMD RYZEN7 9700X\nVGA MSI RTX5070TI 16G GAMING\nMemoria DDR5 32 GB (2x16GB) 6000MHz\nMother ASUS B650 DDR5 hasta 128GB\nSSD NVMe 1TB\nFuente Corsair 750W\nCooler Thermalright\nGabinete Corsair 4000D');assert.equal(a.cpu,'Ryzen 7 9700X');assert.equal(a.gpuVram,16);assert.equal(a.ram,32);assert.equal(a.ramModules,2);assert.equal(a.ramFrequency,6000);for(const k of ['motherboard','psu','cooling','case'])assert.ok(a[k]);});
test('table quantity is not confused with price or motherboard capacity',()=>{const a=parseBudget('Motherboard MSI B760 DDR5 192GB\n2 Memoria Kingston Fury 16GB DDR5 5600MHz $120000\nGPU RTX4060 8GB\nSSD NVME 500GB $70000');assert.equal(a.ram,32);assert.equal(a.ramModules,2);assert.equal(a.capacity,500);});
test('two disks are preserved and fastest disk is selected as primary',()=>{const a=parseBudget('HDD WD 2TB\nSSD Samsung NVMe 1TB');assert.equal(a.drives.length,2);assert.equal(a.storage,'NVMe');assert.equal(a.capacity,1000);});
test('alternatives are explicit instead of merging hardware from different configurations',()=>{const a=parseBudget('CPU Ryzen 5 7600\nCPU Ryzen 7 9700X\nGPU RTX 4060\nGPU RTX 5070 Ti');assert.equal(a.candidates.cpu.length,2);assert.ok(a.issues.length>=2);assert.equal(a.cpu,'Ryzen 5 7600');});
test('family fallback preserves the original CPU identity and reports its comparable profile',()=>{const cpu=resolveCPU('Ryzen 7 9700');assert.equal(cpu.name,'Ryzen 7 9700');assert.equal(cpu.method,'family');assert.ok(cpu.equivalent);assert.equal(identifyCPU('INTEL CORE I5 14400F'),'Core i5-14400F');});
test('fuzzy matching cannot substitute a different model number',()=>{assert.equal(identifyGPU('RTXX 5070 TI'),'RTX 5070 Ti');assert.notEqual(identifyCPU('Ryzen 7 9700X'),'Ryzen 7 7700X');assert.equal(resolveGPU('RTX 6090'),null);});
test('presets and single-channel memory affect estimates; resolutions stay monotonic',()=>{const low=estimate(s,'1080p','low'),ultra=estimate(s,'1080p','ultra');assert.ok(low.gaming[0].max>ultra.gaming[0].max);for(const g of low.gaming){assert.ok(g.values['1080p'].center>=g.values['1440p'].center);assert.ok(g.values['1440p'].center>=g.values['4K'].center);}assert.ok(estimate({...s,ramModules:1},'1080p','low').gaming[6].max<=low.gaming[6].max);});
test('spatial PDF items form rows despite interleaved extraction order',()=>{const item=(str,x,y)=>({str,height:10,transform:[1,0,0,1,x,y]});assert.equal(reconstructRows([item('16GB',160,700),item('SSD',30,650),item('2',5,700),item('RAM',30,700),item('1TB',160,650)]),'2 RAM 16GB\nSSD 1TB');});


