import {resolveCPU,resolveGPU} from './hardware.mjs';import {GAMES} from './games.mjs';
export {cpus,gpus} from './hardware.mjs';export {detect,parseBudget} from './parser.mjs';
export const RESOLUTIONS=['1080p','1440p','4K'];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));const round=x=>x<20?Math.max(1,Math.round(x)):Math.round(x/5)*5;
export const rating=score=>score>=80?'Muy cómodo':score>=60?'Buen desempeño':score>=35?'Uso moderado':'Limitado';
export const fpsLevel=fps=>fps>=120?'Excelente':fps>=80?'Muy bueno':fps>=55?'Bueno':fps>=30?'Ajustar calidad':'Limitado';
export function estimate(spec,resolution='1080p',preset='high'){
 const cpu=resolveCPU(spec.cpu),gpu=resolveGPU(spec.gpu,spec.gpuVram);const ram=Number(spec.ram);
 if(!spec.cpu?.trim()||!spec.gpu?.trim()||!Number.isFinite(ram)||ram<4||ram>512)return null;
 const warnings=[];const inferred=!cpu||!gpu||cpu.method==='family'||gpu.method==='family';
 if(cpu?.equivalent)warnings.push(`CPU: aproximación por familia comparable a ${cpu.equivalent}. Conservamos el modelo original.`);if(gpu?.equivalent)warnings.push(`GPU: aproximación con ${gpu.equivalent}. Los rangos tienen mayor incertidumbre.`);
 if(!cpu||!gpu)warnings.push('Hardware identificado, pero sin referencia fiable para esta familia. Conservamos la configuración; no inventamos FPS.');
 const c=cpu?.gaming||0,g=gpu?.values||[0,0,0],vram=Number(spec.gpuVram)||gpu?.vram||0;
 const memory=clamp(ram/16,.35,1),channel=Number(spec.ramModules)===1?.9:1,speed=Number(spec.ramFrequency),frequency=speed&&speed<2666?.94:1,quality={low:1.65,high:1.15,ultra:.85}[preset]||1.15;
 // Suite mean × workload profile; CPU ceiling avoids linear FPS scaling.
 // Every game result is modeled, never an exact-config measurement.
 const gaming=GAMES.map(game=>{const values=Object.fromEntries(RESOLUTIONS.map((res,i)=>{
  if(!cpu||!gpu)return[res,null];let capacity=g[i]*game.multiplier*quality;const ceiling=game.cpuCap*c*(preset==='low'?1.15:1)*channel*frequency;
  if(vram&&vram<(res==='4K'?10:res==='1440p'?6:4))capacity*=res==='4K'?.75:.88;
  const center=Math.min(capacity,ceiling,game.id==='gta'?180:game.id==='roblox'?240:Infinity)*memory,uncertainty=inferred?.4:gpu.method==='suite'?.22:.3;const min=round(center*(1-uncertainty));let max=round(center*(1+uncertainty));if(game.id==='gta')max=Math.min(max,185);if(game.id==='roblox')max=Math.min(max,240);if(max<=min)max=min+5;return[res,{min,max,center:round(center),method:'estimated'}];}));return{...game,values,...(values[resolution]||{min:null,max:null})};});
 const demanding=gaming.filter(g=>['fortnite','warzone','gta'].includes(g.id));const summary=RESOLUTIONS.map(res=>{const centers=demanding.map(g=>g.values[res]?.center).filter(Number.isFinite).sort((a,b)=>a-b);const center=centers.length?centers[Math.floor(centers.length/2)]:null;return{resolution:res,level:center===null?'Sin referencia':fpsLevel(center),center};});
 const eligible=summary.filter(s=>s.center>=60&&(s.resolution!=='4K'||vram>=10));const comfortable=eligible.filter(s=>s.center>=120);const recommended=comfortable.at(-1)?.resolution||eligible.at(-1)?.resolution||'1080p';
 const disk=spec.storage==='HDD'?.7:1,creative=cpu?(.55*c+.45*g[0]/61.5):0,cpuWork=cpu?c*(1+Math.log2(Math.max(1,cpu.cores/6))*.2):0;
 const jobs=[['Ofimática',c*Math.min(1,ram/8)*disk*90,'Documentos, planillas y navegación.'],['Multitarea',cpuWork*Math.min(1,ram/32)*disk*65,'Varias apps y pestañas al mismo tiempo.'],['Photoshop',creative*Math.min(1,ram/24)*50,'Fotografía y documentos de tamaño moderado.'],['Premiere Pro',creative*Math.min(1,ram/32)*48,'Edición moderada; codecs y efectos cambian la fluidez.'],['After Effects',cpuWork*Math.min(1,ram/64)*42,'Composiciones ligeras; RAM y caché son decisivas.'],['DaVinci Resolve',(.3*c+.7*g[0]/61.5)*Math.min(1,ram/32)*45,'Color y efectos moderados; depende de VRAM.'],['Edición de video 1080p',creative*Math.min(1,ram/16)*65,'Timeline sencillo; aceleración compatible.'],['Edición de video 4K',creative*Math.min(1,ram/32)*35*(vram>=8?1:.7),'Puede requerir proxies con codecs pesados.'],['Renderizado',cpuWork*Math.min(1,ram/32)*45,'Motor CPU/GPU y escena cambian el resultado.'],['Streaming',(.6*c+.4*g[0]/61.5)*Math.min(1,ram/16)*65,'1080p; preferir encoder de hardware compatible.']].map(([name,value,note])=>{const score=cpu&&gpu?Math.round(clamp(value,5,100)):null;return{name,score,level:score===null?'Sin referencia':rating(score),note};});
 if(ram<16)warnings.push('Menos de 16 GB: puede haber tirones y límites de multitarea.');if(ram<32)warnings.push('Para edición de video y proyectos creativos, 32 GB dan más margen.');if(Number(spec.ramModules)===1)warnings.push('Un solo módulo puede limitar el ancho de banda de memoria.');if(spec.storage==='HDD')warnings.push('Un SSD mejora cargas, cachés y respuesta de aplicaciones.');if(!spec.storage)warnings.push('No se identificó el disco: no impide calcular gaming.');if(gpu?.vram===0)warnings.push('Gráfica integrada: memoria compartida y doble canal influyen mucho.');
 const conclusion=!cpu||!gpu?'Conservamos los componentes identificados. Esta familia necesita datos adicionales para una estimación numérica fiable.':eligible.length?`Recomendamos ${recommended==='1440p'?'1440p / 2K':recommended} con el preset ${preset==='low'?'Competitivo / Low':preset==='ultra'?'Ultra':'High'}. ${summary[2].center>=60?'También ofrece margen para 4K en los títulos evaluados.':recommended==='1080p'?'Para resoluciones mayores, reducí calidad o usá reescalado.':'En 4K conviene ajustar la calidad en juegos exigentes.'}`:'Priorizá 1080p con calidad reducida. En juegos exigentes, esta configuración necesita ajustes para una experiencia fluida.';
 return{gaming,productivity:jobs,summary,recommended,conclusion,warnings,cpu,gpu,preset,resolution,uncertainty:inferred?'alta':'moderada',schemaVersion:2};
}
export function makeBudget(spec,name='Mi presupuesto'){return{id:crypto.randomUUID(),name,spec:structuredClone(spec),createdAt:new Date().toISOString(),schemaVersion:2};}
